### ISSUE TITLE
javascript.options.asmjs

### ISSUE THREAD

**Issue by jawz101** [hallzy/mozilla-hardening#1]
Why disable it when the links referenced say the bugs mentioned were fixed like years ago?
ghacks and that pylluko guy don't seem to keep up with what is actually relevant.

**Comment by hallzy** [comment]
No specific reason... There's the chance another issue could surface and since I don't have any problems having it disabled I didn't really see the point in enabling it. Plus I am really not a fan of JavaScript at all and I tend to block it whenever I can.
